variables:
  #NAS地址
  NAS_URL1: /mnt/百度云对外发布资料/Linux产品线/鲁班猫_瑞芯微RV系列/3-Linux镜像/
  # NAS_URL1: /mnt/百度云内部资料/测试/鲁班猫_瑞芯微RV系列/3-Linux镜像/
  GIT_BRANCH: main
  GIT_DEPTH: 1
  URL_GITLAB: git@gitlab.ebf.local:rockchip/linux_ipc/rv1106_rv1103/rv1106_ipc_linux.git
  URL_GITHUB: https://github.com/LubanCat/RV06_03_Linux_SDK.git

stages: # 分段
  - pack

pack-sdk:
  tags:
    - ENABLE
  stage: pack
  when: manual
  before_script:
    - git config --global user.email "embedfire@embedfire.com"
    - git config --global user.name "LubanCat"
  script:
    # 从gitlab获取sdk仓库
    - git clone --branch=${GIT_BRANCH} --depth=${GIT_DEPTH} ${URL_GITLAB} SDK-DIR
    # 进入sdk仓库目录
    - cd SDK-DIR
    # 获取最后一次提交时间和commit
    - COMMIT_DATE=$(git log -1 --format="%ci" | awk '{print $1}' | sed 's/-//g')
    # - COMMIT_ID=$(git log -1 --format=%h)
    # 设置压缩包名称
    - FILE_NAME="LubanCat_RV1106_RV1103_Linux_SDK"
    # - TAR_NAME="${FILE_NAME}_${COMMIT_DATE}_${COMMIT_ID}.tgz" && echo TAR_NAME=$TAR_NAME
    - TAR_NAME="${FILE_NAME}_${COMMIT_DATE}.tgz" && echo TAR_NAME=$TAR_NAME
    # 替换github地址
    - git remote set-url origin ${URL_GITHUB}
    # 打包：pigz打包更快
    - tar -cvf - .git/ | pigz > $TAR_NAME
    # 显示本地文件列表
    - ls -hl
    # 删除原来的源码包
    - rm -rf $NAS_URL1/${FILE_NAME}*.tgz
    # 发布
    - cp -v $TAR_NAME $NAS_URL1
    # 清理
    - cd .. && rm -rf SDK-DIR

build-sdk:
  tags:
    - ENABLE
  stage: pack
  when: manual
  before_script:
    - git config --global user.email "embedfire@embedfire.com"
    - git config --global user.name "LubanCat"
    - export BR2_DL_DIR=/mnt/百度云内部资料/buildroot_dl
  script:
    # 获取当前路径
    - SDK_PATH=$(pwd)
    - pwd && ls -hl

    # 编译
    - $SDK_PATH/auto-build.sh

    #发布
    - mkdir -p $NAS_URL1
    - cp -rfv $SDK_PATH/output-release/* $NAS_URL1/
